Parameters:
  OrganizationID:
    Type: string
Resources:
  CloudwatchSSMSecurityLogConfig:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Description: Security Logging SSM Parameter for CloudWatch Agent
      Name: /cloudwatch/agent/config/SecurityLogging
      Type: String
      Value: !Sub '
        {
          "logs": {
            "logs_collected": {
              "files": {
                "collect_list": [
                  {
                    "file_path": "c:\\inetpub\\logs\\LogFiles\\W3SVC1\\**.log",
                    "log_group_name": "/ThirdParty/${OrganizationId}/${AWS::AccountId}/Microsoft/iis/${AWS::Region}",
                    "log_stream_name": "/{local_hostname}/{ip_address}/iis",
                    "timezone": "UTC"
                  },
                  {
                    "file_path": "c:\\Windows\\System32\\dns\\dns*T*Z.log",
                    "log_group_name": "/ThirdParty/${OrganizationId}/${AWS::AccountId}/Microsoft/dns/${AWS::Region}",
                    "log_stream_name": "/{local_hostname}/{ip_address}/dns",
                    "timezone": "UTC"
                  }
                ]
              },
              "windows_events": {
                "collect_list": [
                  {
                    "event_name": "Application",
                    "event_levels": [
                      "INFORMATION",
                      "WARNING",
                      "ERROR",
                      "CRITICAL"
                    ],
                    "log_group_name": "/ThirdParty/${OrganizationId}/${AWS::AccountId}/Microsoft/Windows_Event/${AWS::Region}",
                    "log_stream_name": "/{local_hostname}/{ip_address}/Windows/Application",
                    "event_format": "xml"
                  },
                  {
                    "event_name": "Security",
                    "event_levels": [
                      "INFORMATION",
                      "WARNING",
                      "ERROR",
                      "CRITICAL"
                    ],
                    "log_group_name": "/ThirdParty/${OrganizationId}/${AWS::AccountId}/Microsoft/Windows_Event/${AWS::Region}",
                    "log_stream_name": "/{local_hostname}/{ip_address}/Windows/Security",
                    "event_format": "xml"
                  },
                  {
                    "event_name": "System",
                    "event_levels": [
                      "INFORMATION",
                      "WARNING",
                      "ERROR",
                      "CRITICAL"
                    ],
                    "log_group_name": "/ThirdParty/${OrganizationId}/${AWS::AccountId}/Microsoft/Windows_Event/${AWS::Region}",
                    "log_stream_name": "/{local_hostname}/{ip_address}/Windows/System",
                    "event_format": "xml"
                  }
                ]
              }
            }
          }
        }'
      Tier: Advanced
  InstallCloudWatchAgentAssociation:
    Type: 'AWS::SSM::Association'
    Properties:
      AssociationName: InstallCloudWatchAgent
      Name: AWS-ConfigureAWSPackage
      Parameters:
        action:
          - Install
        installationType:
          - Uninstall and reinstall
        name:
          - AmazonCloudWatchAgent
      ScheduleExpression: rate(14 days)
      Targets:
        - Key: InstanceIds
          Values:
            - '*'
  ConfigureCloudWatchAgentAssociation:
    Type: 'AWS::SSM::Association'
    Properties:
      AssociationName: ConfigureCloudWatchAgent
      Name: AmazonCloudWatch-ManageAgent
      Parameters:
        action:
          - configure (append)
        mode:
          - ec2
        optionalConfigurationSource:
          - ssm
        optionalConfigurationLocation:
          - /cloudwatch/agent/config/SecurityLogging
        optionalRestart:
          - 'yes'
      ScheduleExpression: rate(14 days)
      Targets:
        - Key: InstanceIds
          Values:
            - '*'
